sudo: false
language: node_js
node_js: 
  - node

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master