sudo: false
language: node_js
node_js: 
  - node

before_install:
  - npm i -g npm@3.5.2

install:
  - npm ci

cache:
  - npm: false

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
