language: node_js
node_js: 
- 8.10.0
cache: yarn

install:
  - yarn ci

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: dev_ginywiny